# -*- coding: utf-8 -*-
"""Python_bylearn_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OlC8yjFp5s2vsKKU7WOqMpMNxgoqoZ2X

# **JORNADA PYTHON FAIXA PRETA POR BYLEARN Nº3**

# Operadores Lógicos

O objetivo é criar condições compostas.

Ex:

* Se estiver calor **E** está de dia
* Se for sábado **OU** se for domingo



!=          é igual        is not
"""

temperatuda = 'calor'
horario = 'dia'

if temperatuda == 'calor' and horario == 'dia':
  print('Hora do sorvete!')
elif temperatura == 'calor' and horario == 'noite':
  print('Tomar banho')
elif temperatura == 'frio' or temperatura == 'congelando':    
  print('Ficar debaixo do cobertor')
else:
  print('Ligar a TV')

for numero in range(10):
  print(numero)

for numero in range(10):
  print(numero+1)

"""limite inferior é inclusivo

limite superior é exclusivo

"""

for numero in range(1,11):
  print(numero)

for numero in range(1,11,2):
  print(numero)

for numero in range(10,0,-1):
  print(numero)

for i in range(11):
  if i == 5:
    print(i*2)

"""Listas"""

numeros_validos = [1, 3, 5, 7, 9]
numero_escolhido = 3
for numero in numeros_validos:
  if numero == numero_escolhido:
    print('acertou')

nomes = ['Flash', 'Greg', 'Kratos', 'Batman', 'Pooky', 'Felix', 'Doctor', 'Gohan', 'Robin']

for nome in nomes:
  print('O gato se chama', nome)

notas = [10, 7, 9 , 10, 5]
soma = 0
for nota in notas:
  soma = soma + nota

media = soma / len(notas)
print(f'O tamanho da lista é {len(notas)}')
print(f'A média é {media:.3f}')

#retorno
def funcao_retorno():
  return 'luciana', 25, 'smart'


nome, idade, perfil = funcao_retorno()
print(nome)
print(idade)
print(perfil)